language: android

jdk:
- oraclejdk8
env:
  global:
    - UUID_TOKEN=36ed2b7b-f335-4ac9-b6d7-0bf21ffbaa2a
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - extra
script:
  - ./gradlew connectedCheck
after_script:
   - bash <(curl -s https://codecov.io/bash) -t ${UUID_TOKEN}
   - cat ./build/outputs/lint-results.xml

sudo: false
